import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";
import Providers from "@/lib/providers";

const googleSans = localFont({
  src: '../fonts/GoogleSans-VariableFont_GRAD,opsz,wght.ttf',
  variable: '--font-google-sans',
  display: 'swap',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es"
      className={`${googleSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans">
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
